In [204]:
import numpy as np
import pandas as pd

In [205]:
# load rankings
reco_matrix = np.load("reco_matrix.npy")[0]
# scores = np.load("reco_matrix_mapped_scores.npy")[0]
print(reco_matrix.shape)
# print(scores.shape)

(943, 10)


In [206]:
import pickle

with open("score_dicts.pkl", "rb") as file:
    scores = pickle.load(file)

# print("Loaded List of OrderedDicts:", scores)

In [207]:
scores[0]

OrderedDict([(380, 3.8718159198760986),
             (626, 2.7504489421844482),
             (289, 4.069461822509766),
             (489, 3.3604166507720947),
             (822, 3.55192232131958),
             (86, 3.9583373069763184),
             (742, 2.6466009616851807),
             (526, 3.740152359008789),
             (363, 4.002052307128906),
             (10, 3.6479642391204834),
             (547, 4.019968509674072),
             (365, 3.4256670475006104),
             (485, 3.7771217823028564),
             (329, 4.739339351654053),
             (422, 3.703352928161621),
             (519, 2.379232883453369),
             (520, 4.210023403167725),
             (221, 4.615879058837891),
             (984, 3.4941725730895996),
             (643, 3.7058939933776855),
             (658, 3.532073497772217),
             (430, 4.770827293395996),
             (92, 3.829817295074463),
             (302, 3.2692313194274902),
             (665, 4.1489386558532715),
             (510

In [208]:
df_m = pd.read_csv(
    "../data/ml-100K/u.item",
    sep="|",
    names=[
        "movieID",
        "Name",
        "Date",
        "Video_Date",
        "IMDB_URL",
        "unknown",
        "Action",
        "Adventure",
        "Animation",
        "Children's",
        "Comedy",
        "Crime",
        "Documentary",
        "Drama",
        "Fantasy",
        "Film-Noir",
        "Horror",
        "Musical",
        "Mystery",
        "Romance",
        "Sci-Fi",
        "Thriller",
        "War",
        "Western",
    ],
    header=None,
    encoding="latin-1",
)
print(df_m.shape)
df_m = df_m[
    [
        "movieID",
        "Action",
        "Adventure",
        "Animation",
        "Children's",
        "Comedy",
        "Crime",
        "Documentary",
        "Drama",
        "Fantasy",
        "Film-Noir",
        "Horror",
        "Musical",
        "Mystery",
        "Romance",
        "Sci-Fi",
        "Thriller",
        "War",
        "Western",
    ]
]

df_movies_mapped = pd.read_csv(
    "../data/ml-100K/i_id_mapping.csv",
    sep="\t",
    names=["movieID", "itemID"],
    header=None,
    encoding="latin-1",
)
movies = pd.merge(df_m, df_movies_mapped, how="inner", on="movieID")
movies = movies.drop(columns=["movieID"])
movies = movies.sort_values(by="itemID")

(1682, 24)


In [209]:
unique_genres = [
    "Action",
    "Thriller",
    "Romance",
    "Western",
    "Children's",
    "Mystery",
    "Fantasy",
    "Film-Noir",
    "Documentary",
    "Comedy",
    "Adventure",
    "Sci-Fi",
    "Horror",
    "Crime",
    "Musical",
    "War",
    "Animation",
    "Drama",
]
genre = movies[unique_genres]
item_features_numpy = genre.to_numpy()

users = pd.read_csv("../data/ml-100k/u_id_mapping.csv", sep="\t")

users = users.sort_values(by="userID")

users = users.drop(columns=users.columns[0])
gender_map = {"M": 0, "F": 1}
users["Gender"] = users["Gender"].map(gender_map)
user_features_numpy = users.to_numpy()
users

Gender  userID
0         0       0
1         1       1
2         0       2
3         0       3
4         0       4
..      ...     ...
938       1     938
939       0     939
940       1     940
941       1     941
942       0     942

[943 rows x 2 columns]

In [210]:
def create_genre_column(r):
    all_genres = [g for g in unique_genres if r[g] == 1]
    return "|".join(all_genres)


movies["genres"] = movies.apply(create_genre_column, axis=1)
movies

Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
240        0          0          0           0       1      0            0   
300        0          0          0           0       0      1            0   
375        0          0          0           1       1      0            0   
50         0          0          0           0       0      0            0   
344        0          0          0           0       0      1            0   
...      ...        ...        ...         ...     ...    ...          ...   
1248       0          0          0           0       0      0            0   
1192       0          0          0           0       1      0            0   
1176       0          0          0           0       0      0            0   
1261       0          0          0           0       0      0            0   
1327       0          0          0           0       1      0            0   

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
240       0        0          0       0        0        0        0       0   
300       0        0          1       0        0        1        0       0   
375       0        0          0       0        0        0        0       0   
50        1        0          0       0        0        0        1       0   
344       1        0          0       0        0        0        0       0   
...     ...      ...        ...     ...      ...      ...      ...     ...   
1248      1        0          0       0        0        0        0       0   
1192      0        0          0       0        0        0        0       0   
1176      1        0          0       0        0        0        0       0   
1261      1        0          0       0        0        0        0       0   
1327      0        0          0       0        0        0        0       0   

      Thriller  War  Western  itemID                            genres  
240          0    0        0       0                            Comedy  
300          1    0        0       1  Thriller|Mystery|Film-Noir|Crime  
375          0    0        0       2                 Children's|Comedy  
50           0    1        1       3         Romance|Western|War|Drama  
344          0    0        0       4                       Crime|Drama  
...        ...  ...      ...     ...                               ...  
1248         0    0        0    1344                             Drama  
1192         0    0        0    1345                            Comedy  
1176         0    0        0    1346                             Drama  
1261         0    0        0    1347                             Drama  
1327         0    0        0    1348                            Comedy  

[1349 rows x 20 columns]

In [211]:
item_ids = movies["itemID"].to_numpy()
item_ids

array([   0,    1,    2, ..., 1346, 1347, 1348])

In [247]:
# tahsin kheya
# last modified 21/07/2024
import pandas as pd
import os
import numpy as np
import torch
import time
from logging import getLogger
import random
import numpy as np
from scipy.stats import entropy


class Calibration(object):
    def __init__(self, config, movies, top_k, unique_genres, users):
        self.device = "cuda:0" if torch.cuda.is_available() else "cpu"
        self.device = torch.device(self.device)
        # self.logger = getLogger()
        self.reco_distribution = []
        self.kl = []

        # self.logger = getLogger()
        self.top_k = top_k
        self.gkl = []
        self.gender_df = users
        self.actual_genre_dist = pd.read_csv(
            os.path.join(config["user_genre_dist_file"]),
            sep="\t",
        )
        self.actual_genre_dist = self.actual_genre_dist.sort_values(by="userID")
        self.unique_genres = unique_genres
        print(self.actual_genre_dist)

        # self.actual_genre_dist = self.actual_genre_dist.drop(columns=["userID"])

        self.config = config
        self.item_df = movies
        self.actual_distribution_without_id = self.actual_genre_dist.drop(
            columns=["userID"]
        )
        self.actual_distribution_without_id = self.actual_distribution_without_id.drop(
            columns=["user_timestamp_sum"]
        ).to_numpy()

        self.actual_distribution_gender = []

    def get_all_user_recommended_genre_dist(self, topk_reco):
        df_reco = pd.DataFrame(
            {
                "userID": np.repeat(np.arange(topk_reco.shape[0]), self.top_k),
                "itemID": topk_reco.flatten(),
                "rank": np.tile(np.arange(1, self.top_k + 1), topk_reco.shape[0]),
            }
        )

        df_reco["weight_factor"] = 1 / (df_reco["rank"]) ** 0.1
        merged_df = pd.merge(df_reco, self.item_df, on="itemID", how="inner")
        merged_df[self.unique_genres] = merged_df[self.unique_genres].div(
            merged_df[self.unique_genres].sum(axis=1), axis=0
        )

        merged_df[self.unique_genres] = (
            merged_df["weight_factor"].values[:, None] * merged_df[self.unique_genres]
        )

        summed_genre = merged_df.groupby("userID")[unique_genres].sum().reset_index()

        weight_total = merged_df.groupby("userID")["weight_factor"].sum()
        summed_genre["user_weight_factor"] = summed_genre["userID"].map(weight_total)

        summed_genre = summed_genre[unique_genres].div(
            summed_genre["user_weight_factor"], axis=0
        )

        return summed_genre

    def get_recom_distribution(self, reco, uid):
        reco = np.array(reco)
        df_reco = pd.DataFrame(
            {
                "userID": np.repeat(uid, len(reco)),
                "itemID": reco.flatten(),
                "rank": np.tile(np.arange(1, len(reco) + 1), 1),
            }
        )
        df_reco["weight_factor"] = 1 / (df_reco["rank"]) ** 0.1
        merged_df = pd.merge(df_reco, self.item_df, on="itemID", how="inner")

        merged_df[self.unique_genres] = merged_df[self.unique_genres].div(
            merged_df[self.unique_genres].sum(axis=1), axis=0
        )
        merged_df[self.unique_genres] = (
            merged_df["weight_factor"].values[:, None] * merged_df[self.unique_genres]
        )
        summed_genre = merged_df.groupby("userID")[unique_genres].sum().reset_index()

        weight_total = merged_df.groupby("userID")["weight_factor"].sum()
        summed_genre["user_weight_factor"] = summed_genre["userID"].map(weight_total)

        summed_genre = summed_genre[unique_genres].div(
            summed_genre["user_weight_factor"], axis=0
        )
      
        
        return summed_genre[unique_genres].to_numpy()

    def get_kl_div(self, q_dist, p_dist, a, uid):
        
        qg_u = (1 - a) * q_dist + a * p_dist
        kl_div = entropy(p_dist, qg_u, base=10)

        # kl_div = 0
        # diversity_tradeoff=0.001

        # qg_u = (1 - a) * q_dist + a * p_dist
        # pg_u = (1 - diversity_tradeoff) * p_dist + diversity_tradeoff * np.full(len(unique_genres),0.01)
       
        # # nonzero_indices = np.where(p_dist != 0)
        # kl_div = np.sum(
        #     pg_u
        #     * np.log10(pg_u / qg_u)
        # )

        return kl_div

    # def get_gender_representation_one_user(self, reco_dist, uid):
    #     c = []
    #     retVal = []

    #     for i in range(len(self.unique_genres)):
    #         c.append(np.log(reco_dist[i] / self.actual_distribution[uid][i + 1]))
    #     # Assuming self.unique_genres is a list or array-like
    #     genre_columns_count = len(self.unique_genres)

    #     reco_dist_slice = reco_dist[:genre_columns_count]
    #     actual_dist_slice = self.actual_distribution[uid][1 : genre_columns_count + 1]

    #     log_ratios = np.log(reco_dist_slice / actual_dist_slice)
    #     retVal.extend(log_ratios.tolist())

    def compute_diversity_score(self, reco_items, uid, l, scores, user_reco, b):

        # -----------------the diversity term----------------------------------
        alpha = 0.01
        # reco_items=self.reco_distribution[uid]
        sum_score = 0
        # genre proportion of recommedned items
        reco_dist = self.get_recom_distribution(reco_items, uid)[0]
        # print(":)"*10)
        # print(reco_dist)
        # print(":)"*10)
        # print(avg_dist)

        # 1x18 array (it already is, but let's reshape explicitly)
        # reco_dist = avg_dist.reshape(1, -1)
        # normalise values
        # reco_dist = reco_dist / sum(reco_dist[0])
        kl = self.get_kl_div(
             reco_dist,self.actual_distribution_without_id[uid], alpha, uid
        )

        # -----------------the diversity term----------------------------------

        # -----------------the fairness term----------------------------------
        # recommended dist mean for each gender
        male_user_ids = self.gender_df[self.gender_df["Gender"] == 0]["userID"]
        male_user_ids = male_user_ids.to_list()
        gender_genre_dist = self.actual_distribution_gender
        
        # gender_reco_dist = self.get_gender_representation_one_user(reco_dist[0],uid)
        if uid in male_user_ids:
            compare_dist = gender_genre_dist[unique_genres].to_numpy()[1] #this is the female avg genre pref
        else:
            compare_dist = gender_genre_dist[unique_genres].to_numpy()[0]

        # gender_kl = self.get_kl_div(reco_dist[0], compare_dist, alpha, uid)
        gender_kl = self.get_kl_div(reco_dist,compare_dist, alpha, uid)

        # -----------------the fairness term----------------------------------

        for r in range(len(reco_items)):
            sum_score += scores[reco_items[r]]
           
            
        
        # print(f"kl {kl} gender kl {gender_kl} score {sum_score}")

        return (1 - l - b) * sum_score - l * kl - b * gender_kl

    # c.get_improved_reco(reco_matrix,reco_matrix_all_items,reco_matrix_all_scores, users)

    def get_improved_reco(self, top_items, items, scores):

        # reco = torch.cat(batch_matrix_list, dim=0).cpu().numpy()

        # scores = torch.cat(batch_score_list, dim=0).cpu().numpy()
        # self.reco_distribution = self.get_recom_distribution(reco)
        return self.get_new_recommendations(
            reco=top_items, scores=scores, all_items=items
        )

    def get_kl_div_gender(self, female_dist, male_dist, a):
        kl_div = 0
        for i in range(len(self.unique_genres)):
            female_dist = (1 - a) * female_dist[i] + a * male_dist[i]
            if male_dist[i] == 0:
                continue
            kl_div = kl_div + male_dist[i] * np.log10(male_dist[i] / female_dist[i])

        return kl_div

    def get_gender_genre_dist(self, user_reco):
        # gender_df = pd.DataFrame(self.genders.items(), columns=["userID", "gender"])
        actual_dist_gender = pd.merge(
            self.actual_genre_dist, self.gender_df, on="userID"
        )
        gender_genre_weights_a = actual_dist_gender.groupby("Gender")[
            self.unique_genres
        ].mean()
        self.actual_distribution_gender = gender_genre_weights_a.sort_index()

    def get_new_recommendations(self, reco, scores, all_items):
        """reco is 6040x50 and scores is 6040x3416"""

        user_reco_dist = self.get_all_user_recommended_genre_dist(
            reco
        )  # genre proportions of each users' recommended items

        self.get_gender_genre_dist(user_reco_dist)

        #####
        # gender_discriminated_agaisnt = self.get_gender_discriminated_agaisnt(
        #     user_reco_dist
        # )
        # male_user_ids = [user_id for user_id, gender in self.genders.items() if gender == 0]
        # female_user_ids = [user_id for user_id, gender in self.genders.items() if gender == 1]
        # for each gender clculate the skew for each genre:
        b = 0.69  # beta for the fairness term
        l = 0.29  # lambda for the calibration term
        all_users = []

        #####

        top_k = self.top_k

        # n_users, n_items = all_items.shape

        for u in range(0, 5):
            # remaining_items = all_items
            remaining_items = list(range(20))

            #             u_calibrated = [623, 1612, 558, 1087, 1347, 3368, 196, 3256, 3127, 882, 831, 1271, 1870, 2594, 3279, 2624, 393, 1496, 3099, 2414, 1232, 1773, 1313, 610, 500, 2855, 1973, 1872, 3334, 3296, 649, 769, 1573, 2474, 2133, 2161, 3387, 2640, 1583, 3287, 753, 384, 2192, 709, 1981, 3311 ]
            u_calibrated = []
            for k in range(top_k):
                diversity_scores = [
                    self.compute_diversity_score(
                        u_calibrated + [i], u, l, scores[u], user_reco_dist, b
                    )
                    for i in remaining_items
                ]
                max_index = np.argmax(diversity_scores)

                best_item = remaining_items[max_index]
                u_calibrated.append(best_item)
                remaining_items.pop(max_index)
                print(u_calibrated)
                # self.logger.info(u_calibrated)

            # self.logger.info(u_calibrated)

            all_users.append(u_calibrated)

        return np.array(all_users)

In [248]:
config = {"user_genre_dist_file": "../data/ml-100k/pgui.csv"}
# movies = movie df
calibration = Calibration(config, movies, 10, unique_genres, users)
calibration.get_improved_reco(reco_matrix, list(item_ids), scores)

     userID    Action  Thriller   Romance   Western  Children's   Mystery  \
0         0  0.019231  0.000000  0.119658  0.000000    0.021368  0.000000   
1         1  0.159306  0.276137  0.030835  0.027148    0.041044  0.043481   
2         2  0.189453  0.066927  0.053255  0.011719    0.031250  0.007813   
3         3  0.076864  0.056048  0.093108  0.005274    0.013010  0.009494   
4         4  0.129167  0.220833  0.079167  0.000000    0.050000  0.037500   
..      ...       ...       ...       ...       ...         ...       ...   
938     938  0.146258  0.110544  0.096939  0.000000    0.004082  0.006803   
939     939  0.071223  0.086930  0.094604  0.000000    0.013189  0.023381   
940     940  0.114286  0.063492  0.107672  0.000000    0.015873  0.005291   
941     941  0.066667  0.186667  0.070000  0.000000    0.000000  0.076667   
942     942  0.183333  0.117424  0.009091  0.000000    0.024242  0.022727   

      Fantasy  Film-Noir  Documentary    Comedy  Adventure    Sci-Fi  \
0  

array([[17, 16, 10,  1,  3,  2,  8,  6,  0,  9],
       [10,  3,  1,  9,  6,  7,  0,  8, 16, 18],
       [10,  3,  1,  0,  4,  7,  6, 12,  8,  9],
       [ 3, 10,  1,  9,  8,  0,  7, 16,  6,  5],
       [10,  3,  1,  9,  2,  6,  8, 17, 16, 18]])

In [249]:
# tahsin kheya
# last modified 11/12/2024
import pandas as pd
import os
import numpy as np
import torch
import time
from logging import getLogger
import random
import numpy as np
from scipy.stats import entropy

class Calibration(object):
    def __init__(self, config, movies, top_k, unique_genres, users):
        self.device = "cuda:0" if torch.cuda.is_available() else "cpu"
        self.device = torch.device(self.device)
        self.reco_distribution = []
        self.kl = []
        self.top_k = top_k
        self.gkl = []
        self.gender_df = users
        self.actual_genre_dist = pd.read_csv(
            os.path.join(config["user_genre_dist_file"]),
            sep="\t",
        )
        self.actual_genre_dist = self.actual_genre_dist.sort_values(by="userID")
        self.unique_genres = unique_genres
        self.config = config
        self.item_df = movies
        self.actual_distribution_without_id = self.actual_genre_dist.drop(
            columns=["userID"]
        )
        self.actual_distribution_without_id = self.actual_distribution_without_id.drop(
            columns=["user_timestamp_sum"]
        ).to_numpy()
        self.actual_distribution_gender = []

    def get_all_user_recommended_genre_dist(self, topk_reco):
        df_reco = pd.DataFrame(
            {
                "userID": np.repeat(np.arange(topk_reco.shape[0]), self.top_k),
                "itemID": topk_reco.flatten(),
                "rank": np.tile(np.arange(1, self.top_k + 1), topk_reco.shape[0]),
            }
        )
        df_reco["weight_factor"] = 1 / (df_reco["rank"]) ** 0.1
        merged_df = pd.merge(df_reco, self.item_df, on="itemID", how="inner")
        merged_df[self.unique_genres] = merged_df[self.unique_genres].div(
            merged_df[self.unique_genres].sum(axis=1), axis=0
        )
        merged_df[self.unique_genres] = (
            merged_df["weight_factor"].values[:, None] * merged_df[self.unique_genres]
        )
        summed_genre = merged_df.groupby("userID")[self.unique_genres].sum().reset_index()
        weight_total = merged_df.groupby("userID")["weight_factor"].sum()
        summed_genre["user_weight_factor"] = summed_genre["userID"].map(weight_total)
        summed_genre = merged_df.groupby("userID")[self.unique_genres].sum().reset_index()
        summed_genre = summed_genre[self.unique_genres].div(
            summed_genre["user_weight_factor"], axis=0
        )

        return summed_genre

    def get_recom_distribution(self, reco, uid):
        reco = np.array(reco)
        df_reco = pd.DataFrame(
            {
                "userID": np.repeat(uid, len(reco)),
                "itemID": reco.flatten(),
                "rank": np.tile(np.arange(1, len(reco) + 1), 1),
            }
        )
        df_reco["weight_factor"] = 1 / (df_reco["rank"]) ** 0.1
        merged_df = pd.merge(df_reco, self.item_df, on="itemID", how="inner")

        merged_df[self.unique_genres] = merged_df[self.unique_genres].div(
            merged_df[self.unique_genres].sum(axis=1), axis=0
        )
        merged_df[self.unique_genres] = (
            merged_df["weight_factor"].values[:, None] * merged_df[self.unique_genres]
        )
        summed_genre = merged_df.groupby("userID")[self.unique_genres].sum().reset_index()

        weight_total = merged_df.groupby("userID")["weight_factor"].sum()
        summed_genre["user_weight_factor"] = summed_genre["userID"].map(weight_total)

        summed_genre = summed_genre[self.unique_genres].div(
            summed_genre["user_weight_factor"], axis=0
        )
      
        
        return summed_genre[self.unique_genres].to_numpy()

    def get_kl_div(self, q_dist, p_dist, a, uid):
        qg_u = (1 - a) * q_dist + a * p_dist
        kl_div = entropy(p_dist, qg_u, base=10)

        return kl_div


    def compute_diversity_score(self, reco_items, uid, l, scores, b):
        alpha = 0.01
        sum_score = 0

        # -----------------the calibration term----------------------------------
       
        reco_dist = self.get_recom_distribution(reco_items, uid)[0]
        kl = self.get_kl_div(
             reco_dist,self.actual_distribution_without_id[uid], alpha, uid
        )

        # -----------------the calibration term----------------------------------

        # -----------------the fairness term----------------------------------
        # recommended dist mean for each gender
        male_user_ids = self.gender_df[self.gender_df["Gender"] == 0]["userID"]
        male_user_ids = male_user_ids.to_list()
        gender_genre_dist = self.actual_distribution_gender
        if uid in male_user_ids:
            compare_dist = gender_genre_dist[self.unique_genres].to_numpy()[1] #this is the female avg genre pref
        else:
            compare_dist = gender_genre_dist[self.unique_genres].to_numpy()[0]

        gender_kl = self.get_kl_div(reco_dist,compare_dist, alpha, uid)

        # -----------------the fairness term----------------------------------

        for r in range(len(reco_items)):
            sum_score += scores[reco_items[r]]
           
        return (1 - l - b) * sum_score - l * kl - b * gender_kl


    def get_improved_reco(self, top_items, items, scores):
        return self.get_new_recommendations(
            reco=top_items, scores=scores, all_items=items
        )


    def get_gender_genre_dist(self):
        actual_dist_gender = pd.merge(
            self.actual_genre_dist, self.gender_df, on="userID"
        )
        gender_genre_weights_a = actual_dist_gender.groupby("Gender")[
            self.unique_genres
        ].mean()
        self.actual_distribution_gender = gender_genre_weights_a.sort_index()

    def get_new_recommendations(self, reco, scores, all_items):
        """reco is 6040x50 and scores is 6040x3416"""
        self.get_gender_genre_dist()
        b = 0.69  # beta for the fairness term
        l = 0.29  # lambda for the calibration term
        all_users = []
        top_k = self.top_k
        for u in range(0, 3):
            remaining_items = list(range(20))
            u_calibrated = []
            for k in range(top_k):
                diversity_scores = [
                    self.compute_diversity_score(
                        u_calibrated + [i], u, l, scores[u], b
                    )
                    for i in remaining_items
                ]
                max_index = np.argmax(diversity_scores)

                best_item = remaining_items[max_index]
                u_calibrated.append(best_item)
                remaining_items.pop(max_index)
                print(u_calibrated)

            all_users.append(u_calibrated)

        return np.array(all_users)

In [250]:
config = {"user_genre_dist_file": "../data/ml-100k/pgui.csv"}
# movies = movie df
calibration = Calibration(config, movies, 10, unique_genres, users)
print(calibration.get_improved_reco(reco_matrix, list(item_ids), scores))

[17]
[17, 16]
[17, 16, 10]
[17, 16, 10, 1]
[17, 16, 10, 1, 3]
[17, 16, 10, 1, 3, 2]
[17, 16, 10, 1, 3, 2, 8]
[17, 16, 10, 1, 3, 2, 8, 6]
[17, 16, 10, 1, 3, 2, 8, 6, 0]
[17, 16, 10, 1, 3, 2, 8, 6, 0, 9]
[10]
[10, 3]
[10, 3, 1]
[10, 3, 1, 9]
[10, 3, 1, 9, 6]
[10, 3, 1, 9, 6, 7]
[10, 3, 1, 9, 6, 7, 0]
[10, 3, 1, 9, 6, 7, 0, 8]
[10, 3, 1, 9, 6, 7, 0, 8, 16]
[10, 3, 1, 9, 6, 7, 0, 8, 16, 18]
[10]
[10, 3]
[10, 3, 1]
[10, 3, 1, 0]
[10, 3, 1, 0, 4]
[10, 3, 1, 0, 4, 7]
[10, 3, 1, 0, 4, 7, 6]
[10, 3, 1, 0, 4, 7, 6, 12]
[10, 3, 1, 0, 4, 7, 6, 12, 8]
[10, 3, 1, 0, 4, 7, 6, 12, 8, 9]
[[17 16 10  1  3  2  8  6  0  9]
 [10  3  1  9  6  7  0  8 16 18]
 [10  3  1  0  4  7  6 12  8  9]]


In [ ]:
movies[movies["itemID"] == 96]

Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
206       0          0          0           0       1      0            0   

     Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
206      0        0          0       1        0        0        0       0   

     Thriller  War  Western  itemID         genres  
206         0    0        0      96  Comedy|Horror

In [ ]:
p = np.array([0.1, 0.3, 0.6])
q = np.array([0.3, 0.4, 0.3])
# q˜(д|u) = (1 − α) · q(д|u) + α · p(д|u)
q_t = (1 - 0.01) * q + 0.01 * p
print(q_t)

[0.298 0.399 0.303]


In [ ]:
0.99 * 0.3 + 0.01 * 0.1

0.298

In [ ]:
sum([0.298, 0.399, 0.303])

1.0

In [ ]:
sum(
    [
        0.0,
        0.01923077,
        0.0,
        0.11965812,
        0.0,
        0.02136753,
        0.0,
        0.00641026,
        0.0,
        0.02564101,
        0.5769231,
        0.02777778,
        0.01282051,
        0.0,
        0.0,
        0.0,
        0.01495726,
        0.0,
        0.17521365,
    ]
)

0.99999999

In [ ]:
item_index = movies.index.get_loc(0)
item_index

24

In [ ]:
reco = [1, 23, 4]
reco_2 = np.array(reco)
reco_2.flatten()

array([ 1, 23,  4])

In [ ]:
nonzero_indices = np.where(p_dist != 0)

In [ ]:
nonzero_indices

(array([0, 2]),)