In [1]:
from cornac.data import Reader
from cornac.datasets import movielens
from cornac.data import Dataset, FeatureModality
from cornac.eval_methods import RatioSplit, StratifiedSplit
from cornac.metrics import RMSE
from cornac.models import  ItemKNN, UserKNN, NMF, BPR, MF,VAECF, NeuMF,PMF, WMF
# from MF import MF
import pandas as pd
import numpy as np
import cornac
import math
# import seaborn as sns
# import matplotlib.pyplot as plt

/Users/tahsinalamgirkheya/anaconda3/envs/re-ranking/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# rating_data_pd = pd.read_csv(
#     "../data/ml-100K/indexed_interactions.csv",
#     sep="\t",
#     header=0,
#     names=["itemID","_","userID", "Rating", "Gender"],
# )
# # itemID	actual_category	userID	Rating	Gender

# rating_data = rating_data_pd.to_numpy()
# rating_data.__len__()
# rating_data_pd

reader = Reader()
rating_data_pd = pd.read_csv(
    "../data/yelp-100K/indexed_interactions.csv",
    sep="\t",
    header=0,
    names=[ "itemID","Category", "userID","Rating", "Gender"],
)
rating_data = rating_data_pd[["userID", "itemID","Rating"]].to_numpy()
rating_data.__len__()
rating_data_pd


itemID                             Category  userID  Rating Gender
0           0  Food & Restaurants|Drinks & Spirits       0       5      F
1           0  Food & Restaurants|Drinks & Spirits       1       4      F
2           0  Food & Restaurants|Drinks & Spirits       2       5      F
3           0  Food & Restaurants|Drinks & Spirits       3       3      M
4           0  Food & Restaurants|Drinks & Spirits       4       3      F
...       ...                                  ...     ...     ...    ...
97986    1271                   Food & Restaurants    1060       3      F
97987    1271                   Food & Restaurants     161       2      M
97988    1271                   Food & Restaurants      25       3      F
97989    1271                   Food & Restaurants     280       4      F
97990    1271                   Food & Restaurants     955       5      F

[97991 rows x 5 columns]

In [3]:

restaurants = pd.read_csv("../data/yelp-100K/i_id_mapping.csv",sep="\t",
    header=0,
    names=[ "item_id","Category","itemID"])
restaurants=restaurants.sort_values(by="itemID")

unique_categories = [
    "Active Life & Fitness",
    "Arts & Entertainment",
    "Automotive",
    "Bars & Nightlife",
    "Coffee,Tea & Desserts",
    "Drinks & Spirits",
    "Education & Learning",
    "Event Services",
    "Family & Kids",
    "Food & Restaurants",
    "Health & Beauty",
    "Home & Garden",
    "Miscellaneous",
    "Outdoor Activities",
    "Public Services & Community",
    "Shopping & Fashion",
    "Specialty Food & Groceries",
    "Sports & Recreation",
    "Technology & Electronics",
    "Travel & Transportation",
    "Asian",
]
for c in unique_categories:
    restaurants[c] = 0
for index, row in restaurants.iterrows():
    cats = row["Category"].split("|")
    for cat in cats:
        restaurants.at[index, cat] = 1

cat = restaurants[unique_categories]
# cat[:1]
item_features_numpy = cat.to_numpy()
item_features = {
    str(item_id): {"category_" + str(idx): value for idx, value in enumerate(row)}
    for item_id, row in enumerate(item_features_numpy)
}
# ids = list(range(0, 3416))

In [4]:
restaurants

item_id                             Category  itemID  \
0          34  Food & Restaurants|Drinks & Spirits       0   
1         250  Food & Restaurants|Drinks & Spirits       1   
2         759             Asian|Food & Restaurants       2   
3        1085                   Food & Restaurants       3   
4        1122              Travel & Transportation       4   
...       ...                                  ...     ...   
1267   188255                   Food & Restaurants    1267   
1268   188310                   Food & Restaurants    1268   
1269   188449  Food & Restaurants|Bars & Nightlife    1269   
1270   188454                   Food & Restaurants    1270   
1271   188578                   Food & Restaurants    1271   

      Active Life & Fitness  Arts & Entertainment  Automotive  \
0                         0                     0           0   
1                         0                     0           0   
2                         0                     0           0   
3                         0                     0           0   
4                         0                     0           0   
...                     ...                   ...         ...   
1267                      0                     0           0   
1268                      0                     0           0   
1269                      0                     0           0   
1270                      0                     0           0   
1271                      0                     0           0   

      Bars & Nightlife  Coffee,Tea & Desserts  Drinks & Spirits  \
0                    0                      0                 1   
1                    0                      0                 1   
2                    0                      0                 0   
3                    0                      0                 0   
4                    0                      0                 0   
...                ...                    ...               ...   
1267                 0                      0                 0   
1268                 0                      0                 0   
1269                 1                      0                 0   
1270                 0                      0                 0   
1271                 0                      0                 0   

      Education & Learning  ...  Home & Garden  Miscellaneous  \
0                        0  ...              0              0   
1                        0  ...              0              0   
2                        0  ...              0              0   
3                        0  ...              0              0   
4                        0  ...              0              0   
...                    ...  ...            ...            ...   
1267                     0  ...              0              0   
1268                     0  ...              0              0   
1269                     0  ...              0              0   
1270                     0  ...              0              0   
1271                     0  ...              0              0   

      Outdoor Activities  Public Services & Community  Shopping & Fashion  \
0                      0                            0                   0   
1                      0                            0                   0   
2                      0                            0                   0   
3                      0                            0                   0   
4                      0                            0                   0   
...                  ...                          ...                 ...   
1267                   0                            0                   0   
1268                   0                            0                   0   
1269                   0                            0                   0   
1270                   0                            0                   0   
1271                   0                       

In [5]:

users = pd.read_csv("../data/yelp-100K/u_id_mapping.csv", sep="\t",header=0,
    names=[ "user_id","Gender","userID"])
gender_map = {"M": 0, "F": 1}
users["Gender"] = users["Gender"].map(gender_map)
users = users.sort_values(by="userID")
users = users[["Gender", "userID"]]

user_features_numpy = users.to_numpy()
print(user_features_numpy.shape)
# print(item_features_numpy.shape)

(1316, 2)


In [6]:
dataset = rating_data
dataset

array([[   0,    0,    5],
       [   1,    0,    4],
       [   2,    0,    5],
       ...,
       [  25, 1271,    3],
       [ 280, 1271,    4],
       [ 955, 1271,    5]])

In [7]:
users

Gender  userID
0          1       0
1          1       1
2          1       2
3          0       3
4          1       4
...      ...     ...
1311       0    1311
1312       1    1312
1313       1    1313
1314       0    1314
1315       0    1315

[1316 rows x 2 columns]

In [8]:
# ratio_split = StratifiedSplit(
#     data=dataset,
#     test_size=0.2,
#     rating_threshold=0.0,
#     seed=123,
#     verbose=True,
#     chrono=True,
# )
ratio_split = StratifiedSplit(
    data=dataset,
    test_size=0.2,
    rating_threshold=0,
    # val_size=0.1,
    seed=123,
    verbose=True,fmt="UIR"
)

hr_10 = cornac.metrics.HitRatio(k=20)
ndcg_10 = cornac.metrics.NDCG(k=20)
recall_10 = cornac.metrics.Recall(k=20)
prec_10 = cornac.metrics.Precision(k=20)
auc = cornac.metrics.AUC()
map = cornac.metrics.MAP()

epochs = [20, 40, 60, 80, 100]
models = []
# class cornac.models.vaecf.recom_vaecf.
# VAECF(name='VAECF', k=10, autoencoder_structure=[20], act_fn='tanh',
# likelihood='mult', n_epochs=100, batch_size=100, learning_rate=0.001, beta=1.0, trainable=True, verbose=False, seed=None, use_gpu=False)[source]
# for i in range(len(epochs)):
#     models.append(
#     #    PMF(k=5, max_iter=epochs[i], learning_rate=0.001, gamma=0.9, lambda_reg=0.001, name=f'PMF{epochs[i]}', variant='linear', trainable=True, verbose=True, init_params=None, seed=123)
#        WMF(name=f'WMF{epochs[i]}', k=200, lambda_u=0.01, lambda_v=0.01, a=1, b=0.01, learning_rate=0.001, batch_size=128, max_iter=epochs[i], trainable=True, verbose=True, init_params=None, seed=123)
#     )
model = WMF(name=f'WMF{100}', k=200, lambda_u=0.01, lambda_v=0.01, a=1, b=0.01, learning_rate=0.001, batch_size=128, max_iter=100, trainable=True, verbose=True, init_params=None, seed=123)

# model = MF(
#             name=f"MF{40}",
#             k=10,
#             backend="cpu",
#             optimizer="adam",
#             max_iter=40,
#             learning_rate=0.01,
#             batch_size=256,
#             lambda_reg=0.02,
#             dropout=0.0,
#             use_bias=True,
#             early_stop=False,
#             num_threads=0,
#             trainable=True,
#             verbose=False,
#             init_params=None,
#             seed=123,
#         )

# model =  NeuMF(
#            name=f"NeuMFe={80}",
#             num_factors=8,
#             layers=( 32, 16, 8),
#             act_fn="sigmoid",
#             reg=0.0,
#             num_epochs=80,
#             batch_size=256,
#             num_neg=3,
#             lr=0.001,
#             learner="adam",
#             backend="tensorflow",
#             early_stopping=None,
#             trainable=True,
#             verbose=True,
#             seed=123,
#         )
# # model=VAECF(k=10, autoencoder_structure=[20], name="vae100",act_fn="tanh", likelihood="mult", n_epochs=100, batch_size=100, learning_rate=0.001, beta=1.0, seed=123, verbose=True)

models = [model]
cornac.Experiment(
    ratio_split, models=models, metrics=[hr_10, ndcg_10, recall_10, auc, prec_10, map]
).run()

rating_threshold = 0.0
exclude_unknowns = True
---
Training data:
Number of users = 1316
Number of items = 1272
Number of ratings = 77877
Max rating = 5.0
Min rating = 1.0
Global mean = 3.9
---
Test data:
Number of users = 1316
Number of items = 1272
Number of ratings = 20114
Number of unknown users = 0
Number of unknown items = 0
---
Total users = 1316
Total items = 1272

[WMF100] Training started!


100%|██████████| 100/100 [00:03<00:00, 30.72it/s, loss=76.5] 


Learning completed!

[WMF100] Evaluation started!


Ranking: 100%|██████████| 1316/1316 [00:01<00:00, 979.39it/s]


TEST:
...
       |    AUC | HitRatio@20 |    MAP | NDCG@20 | Precision@20 | Recall@20 | Train (s) | Test (s)
------ + ------ + ----------- + ------ + ------- + ------------ + --------- + --------- + --------
WMF100 | 0.7478 |      0.7052 | 0.0644 |  0.0947 |       0.0687 |    0.0953 |    5.2487 |   1.3496



In [9]:
user_ids = users["userID"].to_numpy()
item_ids = restaurants["itemID"].to_numpy()
item_ids

array([   0,    1,    2, ..., 1269, 1270, 1271])

In [10]:
users

Gender  userID
0          1       0
1          1       1
2          1       2
3          0       3
4          1       4
...      ...     ...
1311       0    1311
1312       1    1312
1313       1    1313
1314       0    1314
1315       0    1315

[1316 rows x 2 columns]

In [11]:
user_ids.__len__()

1316

In [12]:
# get the top_k ratings for all users:
top_k = 100
reco_matrix = np.zeros((len(models), len(user_ids), top_k), dtype=int)
reco_matrix_mapped_items = np.zeros(
    (len(models), len(user_ids), len(item_ids)), dtype=int
)
reco_matrix_mapped_scores = np.zeros(
    (len(models), len(user_ids), len(item_ids)), dtype=float
)
reco_matrix_all = np.zeros((len(models), len(user_ids), len(item_ids)), dtype=int)


for u in user_ids:
    for i in range(len(models)):
        reco_items = models[i].recommend(u)
        items_mapped, mapped_scores = models[i].rank(
            user_idx=u, item_indices=list(item_ids)
        )
        reco_matrix_mapped_items[i][u] = items_mapped
        reco_matrix_mapped_scores[i][u] = mapped_scores
        reco_matrix_all[i][u] = reco_items
        reco_matrix[i][u] = reco_items[:top_k]

        # print(reco_matrix[0][3])

In [13]:
reco_matrix[0][1]

array([  55,  915,  546,   48,  883,  750,  244,  256,  309,   13,   85,
        290,  321,  115,  698,  609,   40,  820,  836,  909,  859,  308,
        499,  753,  808,  245,  320,  500,  554,  391,  807,  623,  616,
        191,  113,  163,    3,  973,   62, 1053,  528, 1055, 1031,   44,
        542,  185,  272, 1119, 1060,  141,  154,  167,  414,  523,  757,
        196,  453,  646,  329,  762,   14,  484,  619,  879,  153,  809,
        735,  468,  875, 1173,  406,   76,  779,  681, 1009,  417,  774,
         32,  636, 1011,  873, 1176,  447,  490,  221,  303,  205,  116,
        471, 1170,  796,  951,  765,  408,  371,  561,  396,  544, 1204,
        744])

In [14]:
reco_matrix[0][2]

array([ 260,  534,  553,   42,   73,  725,  419,  294,    0,  357,  879,
       1222, 1057,  813,  112,   56,  648,  475,  358,  387,  757,  458,
        310,   24,  132,   62,  167,  501, 1176,  334,   60,  309,  696,
        633, 1170, 1031,  592,   34,  848,  273,  113,  414,  869,  765,
        254,   64,   55, 1084,  823, 1095,  125, 1163,  455,   30,  185,
        555,  271,  234,  563,   29,  394, 1191,  468,   96, 1080,  619,
        562, 1060,  601,  820,  342,  807,  935,  497,  353,  874,  109,
        329,  726,  588,  525,  915,    4,   13,  596,  142, 1184,    2,
        426,  883, 1027,  634,   78,  229,  399,  308, 1053,  773,  872,
        290])

In [23]:
test_set_data = pd.DataFrame(ratio_split.test_set.uir_tuple).transpose()
test_set_data.columns = ["uid", "iid", "rating"]
test_set_data = test_set_data.astype({"uid": "int", "iid": "int", "rating": "int"})
r_global_uid_map = {v: k for k, v in ratio_split.global_uid_map.items()}
r_global_iid_map = {v: k for k, v in ratio_split.global_iid_map.items()}

test_set_data["uid"] = test_set_data["uid"].map(r_global_uid_map)
test_set_data["iid"] = test_set_data["iid"].map(r_global_iid_map)
test_set_data

uid   iid  rating
0         0   407       1
1         0   505       5
2         0   631       5
3         0  1032       1
4         0   266       1
...     ...   ...     ...
20109  1315   690       3
20110  1315   214       4
20111  1315  1223       4
20112  1315   997       4
20113  1315   994       3

[20114 rows x 3 columns]

In [24]:
train_set_data = pd.DataFrame(ratio_split.train_set.uir_tuple).transpose()
train_set_data.columns = ["uid", "iid", "rating"]
train_set_data = train_set_data.astype({"uid": "int", "iid": "int", "rating": "int"})
r_global_uid_map = {v: k for k, v in ratio_split.global_uid_map.items()}
r_global_iid_map = {v: k for k, v in ratio_split.global_iid_map.items()}

train_set_data["uid"] = train_set_data["uid"].map(r_global_uid_map)
train_set_data["iid"] = train_set_data["iid"].map(r_global_iid_map)

In [26]:
train_set_data

uid   iid  rating
0         0    25       4
1         0   900       5
2         0   774       2
3         0   468       5
4         0   529       2
...     ...   ...     ...
77872  1315   666       4
77873  1315   839       4
77874  1315   348       4
77875  1315   824       4
77876  1315  1149       2

[77877 rows x 3 columns]

In [25]:
test_set_data.to_csv("testing_set_seed123_yelp100k.csv", index=False, header=False)


In [27]:
train_set_data.to_csv("training_set_seed123_yelp100k.csv", index=False, header=False)


In [15]:
np.save("reco_matrix_wmf_yelp100k_100",reco_matrix)


In [1]:
reco_matrix[0].shape

NameError: name 'reco_matrix' is not defined

In [16]:
from collections import OrderedDict
# uid_map (OrderDict, required) – The dictionary containing mapping from user original ids to mapped integer indices.

# iid_map (OrderDict, required) – The dictionary containing mapping from item original ids to mapped integer indices.
sorted_by_values = OrderedDict(sorted(models[0].iid_map.items(), key=lambda item: item[1]))
keys_sorted_by_values = list(sorted_by_values.keys())

reco_items_scores_all = [OrderedDict() for _ in range(len(user_ids))]

for u in user_ids:
    actual_index_u = u
    mapped_index_u = models[0].uid_map[actual_index_u]
    # print(f"u {u} mapped u {mapped_index_u}")
    
    # for i in item_ids:
    mapped_scores = reco_matrix_mapped_scores[0][mapped_index_u]
    ordered_dict = OrderedDict(zip(keys_sorted_by_values, mapped_scores))
    reco_items_scores_all[actual_index_u] = ordered_dict
    
    
    

In [1]:
reco_items_scores_all[0]

NameError: name 'reco_items_scores_all' is not defined

In [17]:
models[0].uid_map.items()

odict_items([(101, 0), (845, 1), (705, 2), (20, 3), (635, 4), (593, 5), (153, 6), (37, 7), (915, 8), (522, 9), (810, 10), (18, 11), (34, 12), (809, 13), (239, 14), (749, 15), (889, 16), (928, 17), (542, 18), (501, 19), (342, 20), (175, 21), (116, 22), (144, 23), (618, 24), (118, 25), (860, 26), (335, 27), (263, 28), (825, 29), (405, 30), (942, 31), (867, 32), (286, 33), (393, 34), (224, 35), (146, 36), (792, 37), (416, 38), (652, 39), (147, 40), (368, 41), (773, 42), (727, 43), (194, 44), (246, 45), (75, 46), (446, 47), (76, 48), (461, 49), (793, 50), (912, 51), (110, 52), (504, 53), (84, 54), (627, 55), (621, 56), (42, 57), (594, 58), (728, 59), (301, 60), (214, 61), (668, 62), (937, 63), (484, 64), (274, 65), (685, 66), (526, 67), (776, 68), (121, 69), (139, 70), (108, 71), (679, 72), (207, 73), (111, 74), (65, 75), (587, 76), (143, 77), (322, 78), (392, 79), (770, 80), (299, 81), (838, 82), (690, 83), (630, 84), (27, 85), (829, 86), (11, 87), (676, 88), (26, 89), (380, 90), (490, 91

In [18]:
models[0].iid_map.items()

odict_items([(177, 0), (289, 1), (153, 2), (361, 3), (321, 4), (723, 5), (983, 6), (60, 7), (949, 8), (140, 9), (113, 10), (136, 11), (1024, 12), (311, 13), (347, 14), (240, 15), (111, 16), (52, 17), (31, 18), (297, 19), (320, 20), (88, 21), (367, 22), (489, 23), (490, 24), (568, 25), (355, 26), (985, 27), (68, 28), (402, 29), (95, 30), (710, 31), (203, 32), (175, 33), (426, 34), (161, 35), (722, 36), (488, 37), (405, 38), (445, 39), (841, 40), (771, 41), (698, 42), (450, 43), (415, 44), (83, 45), (302, 46), (11, 47), (364, 48), (388, 49), (124, 50), (336, 51), (955, 52), (1008, 53), (265, 54), (1170, 55), (268, 56), (637, 57), (188, 58), (298, 59), (41, 60), (1037, 61), (1082, 62), (529, 63), (165, 64), (198, 65), (847, 66), (158, 67), (499, 68), (305, 69), (500, 70), (73, 71), (267, 72), (761, 73), (1066, 74), (1110, 75), (350, 76), (832, 77), (687, 78), (913, 79), (306, 80), (514, 81), (810, 82), (1010, 83), (1124, 84), (1122, 85), (412, 86), (644, 87), (562, 88), (1138, 89), (196, 

In [19]:
i,s=models[0].rank(98, item_ids)
print(s.__len__())
np.argsort(s)[-10:][::-1]

1348


array([303,  17,  25, 193, 136,   9, 466, 380, 147, 421])

In [ ]:
matching_keys = [key for key, value in models[0].iid_map.items() if value == 35]
matching_keys


In [ ]:
reco_items_scores_all.__len__()

In [17]:
import pickle
with open('score_dicts_wmf_yelp100k.pkl', 'wb') as file:
    pickle.dump(reco_items_scores_all, file)

print("List of OrderedDicts saved to 'score_dicts.pkl'.")


List of OrderedDicts saved to 'score_dicts.pkl'.


In [ ]:
reco_matrix[0][0]

In [ ]:
reco_items_scores_all[98]

In [ ]:
x = OrderedDict(sorted(reco_items_scores_all[772].items(), key=lambda item: item[1], reverse=True))
x
