In [2]:
import numpy as np
import pandas as pd

In [3]:
test_set = pd.read_csv("../data/ml-100K/testing_set_seed123_ml100k.csv",sep=",",
    header=None,
    names=["userID", "itemID", "Rating"],)
test_set


userID  itemID  Rating
0         101     450       4
1         101     365       2
2         101     285       4
3         101     310       3
4         101     460       4
...       ...     ...     ...
20234     724     710       3
20235     724     130       4
20236     724     280       4
20237     724     175       4
20238     724     645       4

[20239 rows x 3 columns]

In [4]:
test_set[test_set["userID"]==44]

userID  itemID  Rating
7482      44     139       5
7483      44     604       5
7484      44     380       5
7485      44     798       5

In [18]:
all_users_tp = test_set.groupby('userID')['itemID'].apply(list).tolist()
all_users_tp.__len__()

943

In [5]:
test_set[test_set["userID"]==1]

userID  itemID  Rating
5407       1     837       3
5408       1      31       5
5409       1     450       4
5410       1     528       4
5411       1     246       4
5412       1      43       3
5413       1     907       4
5414       1    1305       2
5415       1      10       4
5416       1    1105       4
5417       1      25       4
5418       1      48       4
5419       1     574       4
5420       1       1       3
5421       1     930       4
5422       1     280       3
5423       1     145       4
5424       1     883       4
5425       1     243       3

In [9]:
reco_matrix = np.load("../test/reco_matrix_mf_100k.npy")

In [7]:
reco_matrix[0][1]

array([200, 174, 239, 297, 180, 277, 357,  36, 240,  31, 189, 510, 536,
       101,  66, 260, 125,  58,  78, 710])

In [8]:
from HitRation import HitRatio
hr=HitRatio(20)
alist=[]
sum_hr=0
for u in range(reco_matrix[0].shape[0]):
    x=hr.compute(all_users_tp[u],reco_matrix[0][u])
    print(f"x {x} tp {all_users_tp[u]} reco {reco_matrix[0][u]}")
    # alist.append(x)
    sum_hr=sum_hr+x
    # print(x)
plain_hr=sum_hr/reco_matrix[0].shape[0]
plain_hr

::::::::::
[200 174 239 297 180 277 357  36 240  31 189 510 536 101  66 260 125  58
  78 710]
[519, 626, 437, 927, 983, 649, 363, 821]
0
::::::::::
x 0.0 tp [519, 626, 437, 927, 983, 649, 363, 821] reco [200 174 239 297 180 277 357  36 240  31 189 510 536 101  66 260 125  58
  78 710]
::::::::::
[200 174 239 297 180 277 357  36 240  31 189 510 536 101  66 260 125  58
  78 710]
[837, 31, 450, 528, 246, 43, 907, 1305, 10, 1105, 25, 48, 574, 1, 930, 280, 145, 883, 243]
1
::::::::::
x 1.0 tp [837, 31, 450, 528, 246, 43, 907, 1305, 10, 1105, 25, 48, 574, 1, 930, 280, 145, 883, 243] reco [200 174 239 297 180 277 357  36 240  31 189 510 536 101  66 260 125  58
  78 710]
::::::::::
[200 174 239 297 180 277 357  36 240  31 189 510 536 101  66 260 125  58
  78 710]
[502, 197, 609, 253, 6, 436, 46, 759, 62, 790, 305, 136, 884, 146, 23, 14, 748, 474, 443, 525, 456, 536, 368, 25, 472, 354]
1
::::::::::
x 1.0 tp [502, 197, 609, 253, 6, 436, 46, 759, 62, 790, 305, 136, 884, 146, 23, 14, 748, 474, 443

0.4029692470837752

In [8]:
pd_b50= pd.read_csv("results/greedy/res_top10_b50.csv",sep=",",)
    # header=None,
    # names=["userID", "itemID", "Rating"],)
reco_matrix_b50=[]
for i in range(len(pd_b50)):
    reco_matrix_b50.append(np.array(pd_b50.iloc[i][1:]))
    # results/greedy/res_top10_b69.csv
# reco_matrix_l49b49

FileNotFoundError: [Errno 2] No such file or directory: 'results/greedy/res_top10_b50.csv'

In [31]:
from HitRation import HitRatio
hr=HitRatio(10)
alist=[]
sum_hr=0
for u in range(reco_matrix[0].shape[0]):
    x=hr.compute(all_users_tp[u],reco_matrix_b50[u])
    # alist.append(x)
    sum_hr=sum_hr+x
    # print(x)
hrl29b69=sum_hr/reco_matrix[0].shape[0]
hrl29b69
    

0.2598091198303287

In [32]:
# pd_l49b49= pd.read_csv("../results/res_top10l49b49.csv",sep=",",)
pd_b50= pd.read_csv("results/greedy/res_top10_b70.csv",sep=",",)

    # header=None,
    # names=["userID", "itemID", "Rating"],)
reco_matrix_b70=[]
for i in range(len(pd_b50)):
    reco_matrix_b70.append(np.array(pd_b50.iloc[i][1:]))
from HitRation import HitRatio
hr=HitRatio(10)
alist=[]
sum_hr=0
for u in range(reco_matrix[0].shape[0]):
    x=hr.compute(all_users_tp[u],reco_matrix_b70[u])
    # alist.append(x)
    sum_hr=sum_hr+x
    # print(x)
hrb70=sum_hr/reco_matrix[0].shape[0]
hrb70
    
# reco_matrix_l49b49

0.23435843054082714

In [30]:
movies = pd.read_csv(
    "../data/ml-100K/i_id_mapping_genre.csv",
    sep="\t",
    names=[
        "item_id",
        "Name",
        "genres",
        "itemID"
    ],
    header=0,
    # encoding="latin-1",
)
movies = movies.drop(columns=["item_id"])
movies = movies.sort_values(by="itemID")
unique_genres = [
    "Action",
    "Thriller",
    "Romance",
    "Western",
    "Children's",
    "Mystery",
    "Fantasy",
    "Film-Noir",
    "Documentary",
    "Comedy",
    "Adventure",
    "Sci-Fi",
    "Horror",
    "Crime",
    "Musical",
    "War",
    "Animation",
    "Drama",
]
for genre in unique_genres:
    movies[genre] = 0
    
for index, row in movies.iterrows():
    if row["itemID"]!=793:
        genres = row["genres"].split("|")
    else:
        genres=""
    for genre in genres:
        movies.at[index, genre] = 1


movies

users = pd.read_csv("../data/ml-100k/u_id_mapping_demographic_.csv", sep="\t")
users = users.sort_values(by="userID")

# users = users.drop(columns=users.columns[0])
gender_map = {"M": 0, "F": 1}
users["Gender"] = users["Gender"].map(gender_map)
user_features_numpy = users.to_numpy()
users



FileNotFoundError: [Errno 2] No such file or directory: '../data/ml-100K/i_id_mapping_genre.csv'

In [26]:
import os
os.chdir("/Users/tahsinalamgirkheya/Desktop/work/reranking_fairnes")


In [27]:
from mymetrics.GenrePrecisionMulti import GenrePrecisionMulti
####Import Metrics####
# from mymetrics.GenrePrecision import GenrePrecision

top_k = 10
###intialize them
gp = GenrePrecisionMulti(users, unique_genres, top_k)

NameError: name 'users' is not defined

In [76]:
gp_plain = gp.compute(reco_matrix[0], movies, "Gender")

In [77]:
gp_plain

(0.15616970094582036,
 array([1.55242925e-02, 3.85968509e-03, 1.83571611e-02, 4.58809433e-03,
        3.05263973e-03, 2.46455452e-03, 9.48098336e-05, 9.04178740e-04,
        4.17965119e-03, 1.15429720e-02, 1.20666721e-02, 1.13641408e-02,
        1.18386092e-03, 1.46865489e-02, 6.82366556e-03, 2.90443387e-04,
        6.97272794e-03, 3.82136023e-02]))

In [29]:
os.chdir("/Users/tahsinalamgirkheya/Desktop/work/reranking_fairnes")

In [24]:
os.chdir("/Users/tahsinalamgirkheya/Desktop/work/reranking_fairnes/metrics")


In [95]:

# pd_l49b49= pd.read_csv("../results/res_top10l49b49.csv",sep=",",)results/normalized/restop10_occupartion_b50.csv
pd_b50_occ= pd.read_csv("results/normalized/restop10_occupartion_b50.csv",sep=",",)
# results/greedy/occupation/res_top10_b50.csv
    # header=None,
    # results/normalized/retop10_gender_b50.csv
    # names=["userID", "itemID", "Rating"],)
reco_matrix_b50=[]
for i in range(len(pd_b50_occ)):
    reco_matrix_b50.append(np.array(pd_b50_occ.iloc[i][1:]))
os.chdir("/Users/tahsinalamgirkheya/Desktop/work/reranking_fairnes/metrics")
    
from HitRation import HitRatio
hr=HitRatio(10)
alist=[]
sum_hr=0
for u in range(reco_matrix[0].shape[0]):
    x=hr.compute(all_users_tp[u],reco_matrix_b50[u])
    # alist.append(x)
    sum_hr=sum_hr+x
    # print(x)
hrb50=sum_hr/reco_matrix[0].shape[0]
hrb50
    
# reco_matrix_l49b49

0.2205726405090138

In [ ]:

# pd_l49b49= pd.read_csv("../results/res_top10l49b49.csv",sep=",",)results/normalized/restop10_occupartion_b50.csv
pd_b50_occ= pd.read_csv("results/normalized/retop10_gender_b50.csv",sep=",",)
# results/greedy/occupation/res_top10_b50.csv
    # header=None,
    # results/normalized/retop10_gender_b50.csv
    # names=["userID", "itemID", "Rating"],)
reco_matrix_b50=[]
for i in range(len(pd_b50_occ)):
    reco_matrix_b50.append(np.array(pd_b50_occ.iloc[i][1:]))
os.chdir("/Users/tahsinalamgirkheya/Desktop/work/reranking_fairnes/metrics")
    
from HitRation import HitRatio
hr=HitRatio(10)
alist=[]
sum_hr=0
for u in range(reco_matrix[0].shape[0]):
    x=hr.compute(all_users_tp[u],reco_matrix_b50[u])
    # alist.append(x)
    sum_hr=sum_hr+x
    # print(x)
hrb50=sum_hr/reco_matrix[0].shape[0]
hrb50
    
# reco_matrix_l49b49

In [84]:
np.array(reco_matrix_b50)

array([[ 430,  693,  357, ...,  321,  619,  329],
       [ 843,  474,   57, ...,  319,  614,  918],
       [ 161,  180,  858, ...,  103,  371,  710],
       ...,
       [ 760,   17, 1009, ...,  424, 1184,  207],
       [1031,   46,  978, ...,   88,  511,  650],
       [  30,  106,  501, ...,  632,  683,  720]])

In [51]:
reco_matrix[0][0]

array([1192,   96,  619,  430,  157,  329,  994,  566,  239,  321])

In [98]:
gp_new = gp.compute(np.array(reco_matrix_b50), movies, "Occupation_Code")
gp_new

(0.08162962414272333,
 array([0.00636107, 0.00682772, 0.00356263, 0.00188461, 0.00437893,
        0.00455127, 0.00149477, 0.0048778 , 0.00014242, 0.00822641,
        0.0054826 , 0.0049809 , 0.00697723, 0.00242619, 0.00558255,
        0.00298825, 0.00373962, 0.00714464]))

In [20]:
pwd

'/Users/tahsinalamgirkheya/Desktop/work/reranking_fairnes/metrics'

In [22]:

# pd_l49b49= pd.read_csv("../results/res_top10l49b49.csv",sep=",",)results/normalized/restop10_occupartion_b50.csv
pd_b70_occ= pd.read_csv("results/normalized/restop10_occupartion_b70.csv",sep=",",)
# results/greedy/occupation/res_top10_b50.csv
    # header=None,
    # results/normalized/restop10_occupartion_b70.csv
    # names=["userID", "itemID", "Rating"],)
reco_matrix_b70=[]
for i in range(len(pd_b70_occ)):
    reco_matrix_b70.append(np.array(pd_b70_occ.iloc[i][1:]))
os.chdir("/Users/tahsinalamgirkheya/Desktop/work/reranking_fairnes/metrics")
    
from HitRation import HitRatio
hr=HitRatio(10)
alist=[]
sum_hr=0
for u in range(reco_matrix[0].shape[0]):
    x=hr.compute(all_users_tp[u],reco_matrix_b70[u])
    # alist.append(x)
    sum_hr=sum_hr+x
    # print(x)
hrb70=sum_hr/reco_matrix[0].shape[0]
hrb70
    
# reco_matrix_l49b49

::::::::::
[ 704  161  189  581  389   96 1192  357  307  619]
[519, 626, 437, 927, 983, 649, 363, 821]
0
::::::::::
::::::::::
[843 474 673 656 918 256 531 624 220 469]
[837, 31, 450, 528, 246, 43, 907, 1305, 10, 1105, 25, 48, 574, 1, 930, 280, 145, 883, 243]
0
::::::::::
::::::::::
[ 47 398  52 371 118 917 361 115 321  49]
[502, 197, 609, 253, 6, 436, 46, 759, 62, 790, 305, 136, 884, 146, 23, 14, 748, 474, 443, 525, 456, 536, 368, 25, 472, 354]
0
::::::::::
::::::::::
[ 67 150 216 486 623  26 596  44  94 225]
[8, 291, 546, 925, 1098, 524, 523, 526, 927, 627, 215, 197, 1057, 1121, 316, 525, 65, 821, 285, 1064, 1021, 995, 79, 1024, 358, 296, 786, 417, 362, 639, 205, 570, 805, 557, 328, 1154, 701, 454, 33, 804, 740, 13, 612, 768, 705, 474, 680, 193]
0
::::::::::
::::::::::
[437 112 100 184 104 407 293  99 785  78]
[187, 963, 661, 252]
0
::::::::::
::::::::::
[ 693  430  311  558  428  135  566   29 1052  180]
[94, 350, 501, 84, 542, 17, 33, 408, 951, 273, 444, 25, 686, 272, 95, 1104, 90

0.20572640509013787

In [23]:
gp_2 = gp.compute(np.array(reco_matrix_b70),movies,"Occupation_Code")
gp_2

NameError: name 'gp' is not defined

In [90]:
reco_matrix_b70[0]

array([ 437,  150,  673,  195,  389,  361,  180,  710, 1192,  321])

In [24]:
gp_3 = gp.compute(np.array(reco_matrix_l69b29),movies)
sum(abs(gp_3))

0.05702796356030189

In [25]:
#printitng results nicely



In [64]:
print("+"*50)
print("for equation \n (1 - l - b) * sum of scores for selected items (reco)\n - l * kl div of past genre prop x reco genre prop\n - b * kl div of past gender genre prop x reco genre prop)")
print("+"*50)
data = [
    ["      ","l=.29 b=.69", "l=.49 b=.49" , "l=.69 b=.29" ,"plain"], 
    ["Hitratio@10",  round(hrl29b69,4),round(hrl49b49,4), round(hrl69b29,4),round(plain_hr,4)],                              
    ["Gender Bias", round(sum(abs(gp_1)),4),round(sum(abs(gp_2)),4),round(sum(abs(gp_3)),4), 0.1561],                         
]


print("{:<12} {:<15} {:<15} {:<15} {:<15}".format(*data[0]))  
print("-" * 50)                                      
for row in data[1:]:                                
    print("{:<12} {:<15} {:<15} {:<15} {:<15}".format(*row))
    
print("+"*50)
print("for equation \n (1 - l - b) * sum of scores for selected items (reco)\n - l * kl div of past genre prop x reco genre prop\n - b * kl div of recommended gender genre prop x reco genre prop)")
print("+"*50)
data = [
    ["      ", "l=.49 b=.49" , "l=.69 b=.29" , "l=.29 b=.29" ,"plain"], 
    ["Hitratio@10",round(hr_recol49b49,4), round(hr_recol69b29,4),round(hr_recol29b29,4),round(plain_hr,4)],                              
    ["Gender Bias",round(sum(abs(gp_reco_1)),4),round(sum(abs(gp_reco_2)),4),round(sum(abs(gp_reco_3)),4), 0.1561],                         
]


print("{:<12} {:<15} {:<15} {:<15} {:<15} ".format(*data[0]))  
print("-" * 50)                                      
for row in data[1:]:                                
    print("{:<12} {:<15} {:<15} {:<15} {:<15} ".format(*row))



++++++++++++++++++++++++++++++++++++++++++++++++++
for equation 
 (1 - l - b) * sum of scores for selected items (reco)
 - l * kl div of past genre prop x reco genre prop
 - b * kl div of past gender genre prop x reco genre prop)
++++++++++++++++++++++++++++++++++++++++++++++++++
             l=.29 b=.69     l=.49 b=.49     l=.69 b=.29     plain          
--------------------------------------------------
Hitratio@10  0.2609          0.2704          0.3086          0.3595         
Gender Bias  0.0301          0.0298          0.057           0.1561         
++++++++++++++++++++++++++++++++++++++++++++++++++
for equation 
 (1 - l - b) * sum of scores for selected items (reco)
 - l * kl div of past genre prop x reco genre prop
 - b * kl div of recommended gender genre prop x reco genre prop)
++++++++++++++++++++++++++++++++++++++++++++++++++
             l=.49 b=.49     l=.69 b=.29     l=.29 b=.29     plain           
--------------------------------------------------
Hitratio@10  0.2407 

In [29]:
import os
os.chdir("/Users/tahsinalamgirkheya/Desktop/work/reranking_fairnes/metrics")


In [32]:
pdreco_l49b49= pd.read_csv("../results/reco_dist_gender/res_top10l49b49.csv",sep=",",)
    # header=None,
    # names=["userID", "itemID", "Rating"],)
reco_matrix_reco_l49b49=[]
for i in range(len(pdreco_l49b49)):
    reco_matrix_reco_l49b49.append(np.array(pdreco_l49b49.iloc[i][1:]))
    
# reco_matrix_l49b49

In [35]:

hr=HitRatio(10)
alist=[]
sum_hr=0
for u in range(reco_matrix[0].shape[0]):
    x=hr.compute(all_users_tp[u],reco_matrix_reco_l49b49[u])
    # alist.append(x)
    sum_hr=sum_hr+x
    # print(x)
hr_recol49b49=sum_hr/reco_matrix[0].shape[0]
hr_recol49b49
    

0.24072110286320256

In [37]:
gp_reco_1 = gp.compute(np.array(reco_matrix_reco_l49b49),movies)
sum(abs(gp_reco_1))

0.024419404807464518

In [43]:
pdreco_l69b29= pd.read_csv("../results/reco_dist_gender/res_topl69b29.csv",sep=",",)
    # header=None,
    # names=["userID", "itemID", "Rating"],)
reco_matrix_reco_l69b29=[]
for i in range(len(pdreco_l49b49)):
    reco_matrix_reco_l69b29.append(np.array(pdreco_l69b29.iloc[i][1:]))
    
# reco_matrix_l49b49

In [44]:

hr=HitRatio(10)
alist=[]
sum_hr=0
for u in range(reco_matrix[0].shape[0]):
    x=hr.compute(all_users_tp[u],reco_matrix_reco_l69b29[u])
    # alist.append(x)
    sum_hr=sum_hr+x
    # print(x)
hr_recol69b29=sum_hr/reco_matrix[0].shape[0]
hr_recol69b29
    

0.24284199363732767

In [61]:
gp_reco_2 = gp.compute(np.array(reco_matrix_reco_l69b29),movies)
sum(abs(gp_reco_2))

0.05035359628394449

In [49]:
pwd

'/Users/tahsinalamgirkheya/Desktop/work/reranking_fairnes/metrics'

In [50]:
pdreco_l29b29= pd.read_csv("../results/reco_dist_gender/res_top10l29b29.csv",sep=",",)
    # header=None,
    # names=["userID", "itemID", "Rating"],)
reco_matrix_reco_l29b29=[]
for i in range(len(pdreco_l29b29)):
    reco_matrix_reco_l29b29.append(np.array(pdreco_l29b29.iloc[i][1:]))
    
# reco_matrix_l49b49

In [51]:

hr=HitRatio(10)
alist=[]
sum_hr=0
for u in range(reco_matrix[0].shape[0]):
    x=hr.compute(all_users_tp[u],reco_matrix_reco_l29b29[u])
    # alist.append(x)
    sum_hr=sum_hr+x
    # print(x)
hr_recol29b29=sum_hr/reco_matrix[0].shape[0]
hr_recol29b29
    

0.271474019088017

In [53]:
gp_reco_3 = gp.compute(np.array(reco_matrix_reco_l29b29),movies)
sum(abs(gp_reco_3))

0.09345367383675837

In [56]:
pdreco_l29b69= pd.read_csv("../results/reco_dist_gender/res_top10l29b69.csv",sep=",",)
    # header=None,
    # names=["userID", "itemID", "Rating"],)
reco_matrix_reco_l29b69=[]
for i in range(len(pdreco_l29b69)):
    reco_matrix_reco_l29b69.append(np.array(pdreco_l29b69.iloc[i][1:]))
    
# reco_matrix_l49b49

In [57]:

hr=HitRatio(10)
alist=[]
sum_hr=0
for u in range(reco_matrix[0].shape[0]):
    x=hr.compute(all_users_tp[u],reco_matrix_reco_l29b69[u])
    # alist.append(x)
    sum_hr=sum_hr+x
    # print(x)
hr_recol29b69=sum_hr/reco_matrix[0].shape[0]
hr_recol29b69
    

0.22269353128313893

In [58]:
gp_reco_4 = gp.compute(np.array(reco_matrix_reco_l29b69),movies)
sum(abs(gp_reco_4))

0.04324718491385155

In [27]:
# sum score 3.3451600074768066 fairness -67.75200665458023 

(3.3451600074768066-2.2533798217773438)/4.4314069747924805

0.24637326066188947

In [31]:
(-67.75200665458023--72.5915433343418)/ -62.46890066833761

-0.07747113568487185

In [32]:
0.5*0.24637326066188947 -0.5*0.07747113568487185

0.08445106248850881

In [ ]:
score 0.24637326066188947 ft -0.07747113568487185