In [1]:
import numpy as np
import pandas as pd

In [2]:
test_set = pd.read_csv("testing_set_seed123_ml100k.csv",sep=",",
    header=None,
    names=["userID", "itemID", "Rating"],)
test_set

userID  itemID  Rating
0           0     464       4
1           0     431       2
2           0     179       3
3           0     291       3
4           0     928       4
...       ...     ...     ...
20237     942     450       4
20238     942     858       5
20239     942     157       4
20240     942      24       5
20241     942     180       5

[20242 rows x 3 columns]

In [3]:
all_users_tp = test_set.groupby('userID')['itemID'].apply(list).tolist()
all_users_tp.__len__()

943

In [4]:
test_set[test_set["userID"]==1]

userID  itemID  Rating
8        1     746       2
9        1     442       4
10       1     445       2
11       1     280       3
12       1     349       2
13       1     875       4
14       1    1106       4
15       1     370       1
16       1     425       4
17       1     450       4
18       1     931       4
19       1     149       3
20       1     541       5
21       1     574       4
22       1     645       5
23       1     908       4
24       1      25       4
25       1     140       5
26       1    1188       2

In [5]:
reco_matrix = np.load("../test/reco_matrix.npy")

In [6]:
reco_matrix[0][1]

array([110, 319, 220, 374, 918, 745,  99, 607,  57, 191])

In [7]:
from HitRation import HitRatio
hr=HitRatio(10)
alist=[]
sum_hr=0
for u in range(reco_matrix[0].shape[0]):
    x=hr.compute(all_users_tp[u],reco_matrix[0][u])
    # alist.append(x)
    sum_hr=sum_hr+x
    # print(x)
plain_hr=sum_hr/reco_matrix[0].shape[0]
plain_hr

0.35949098621421

In [8]:
pd_b50= pd.read_csv("results/greedy/res_top10_b50.csv",sep=",",)
    # header=None,
    # names=["userID", "itemID", "Rating"],)
reco_matrix_b50=[]
for i in range(len(pd_b50)):
    reco_matrix_b50.append(np.array(pd_b50.iloc[i][1:]))
    # results/greedy/res_top10_b69.csv
# reco_matrix_l49b49

FileNotFoundError: [Errno 2] No such file or directory: 'results/greedy/res_top10_b50.csv'

In [31]:
from HitRation import HitRatio
hr=HitRatio(10)
alist=[]
sum_hr=0
for u in range(reco_matrix[0].shape[0]):
    x=hr.compute(all_users_tp[u],reco_matrix_b50[u])
    # alist.append(x)
    sum_hr=sum_hr+x
    # print(x)
hrl29b69=sum_hr/reco_matrix[0].shape[0]
hrl29b69
    

0.2598091198303287

In [32]:
# pd_l49b49= pd.read_csv("../results/res_top10l49b49.csv",sep=",",)
pd_b50= pd.read_csv("results/greedy/res_top10_b70.csv",sep=",",)

    # header=None,
    # names=["userID", "itemID", "Rating"],)
reco_matrix_b70=[]
for i in range(len(pd_b50)):
    reco_matrix_b70.append(np.array(pd_b50.iloc[i][1:]))
from HitRation import HitRatio
hr=HitRatio(10)
alist=[]
sum_hr=0
for u in range(reco_matrix[0].shape[0]):
    x=hr.compute(all_users_tp[u],reco_matrix_b70[u])
    # alist.append(x)
    sum_hr=sum_hr+x
    # print(x)
hrb70=sum_hr/reco_matrix[0].shape[0]
hrb70
    
# reco_matrix_l49b49

0.23435843054082714

In [7]:
movies = pd.read_csv(
    "../data/ml-100K/i_id_mapping_genre.csv",
    sep="\t",
    names=[
        "item_id",
        "Name",
        "genres",
        "itemID"
    ],
    header=0,
    # encoding="latin-1",
)
movies = movies.drop(columns=["item_id"])
movies = movies.sort_values(by="itemID")
unique_genres = [
    "Action",
    "Thriller",
    "Romance",
    "Western",
    "Children's",
    "Mystery",
    "Fantasy",
    "Film-Noir",
    "Documentary",
    "Comedy",
    "Adventure",
    "Sci-Fi",
    "Horror",
    "Crime",
    "Musical",
    "War",
    "Animation",
    "Drama",
]
for genre in unique_genres:
    movies[genre] = 0
    
for index, row in movies.iterrows():
    if row["itemID"]!=793:
        genres = row["genres"].split("|")
    else:
        genres=""
    for genre in genres:
        movies.at[index, genre] = 1


movies

users = pd.read_csv("../data/ml-100k/u_id_mapping_demographic_.csv", sep="\t")
users = users.sort_values(by="userID")

# users = users.drop(columns=users.columns[0])
gender_map = {"M": 0, "F": 1}
users["Gender"] = users["Gender"].map(gender_map)
user_features_numpy = users.to_numpy()
users



user_id  Age  Gender  Occupation ZipCode  userID  Occupation_Code
195      196   49       0      writer   55105       0               20
185      186   39       1   executive   00000       1                6
21        22   25       0      writer   40206       2               20
243      244   28       0  technician   80525       3               19
165      166   47       0    educator   55113       4                3
..       ...  ...     ...         ...     ...     ...              ...
938      939   26       1     student   33319     938               18
935      936   24       0       other   32789     939               13
929      930   28       1   scientist   07310     940               17
919      920   30       1      artist   90008     941                1
940      941   20       0     student   97229     942               18

[943 rows x 7 columns]

In [20]:
import os
os.chdir("/Users/tahsinalamgirkheya/Desktop/work/reranking_fairnes")


In [9]:
from mymetrics.GenrePrecisionMulti import GenrePrecisionMulti
####Import Metrics####
# from mymetrics.GenrePrecision import GenrePrecision

top_k = 10
###intialize them
gp = GenrePrecisionMulti(users, unique_genres, top_k)

In [16]:
gp_plain = gp.compute(reco_matrix[0], movies, "Occupation_Code")

In [17]:
gp_plain

(0.22287142582228225,
 array([0.02249289, 0.01224595, 0.01370577, 0.00650847, 0.00409774,
        0.00828266, 0.00106846, 0.00648368, 0.00751913, 0.01862701,
        0.01360148, 0.01480981, 0.00841938, 0.01170088, 0.00766703,
        0.00969734, 0.01159488, 0.04434886]))

In [22]:
# pd_l49b49= pd.read_csv("../results/res_top10l49b49.csv",sep=",",)
pd_b50_occ= pd.read_csv("results/greedy/occupation/res_top10_b50.csv",sep=",",)
# results/greedy/occupation/res_top10_b50.csv
    # header=None,
    # names=["userID", "itemID", "Rating"],)
reco_matrix_b50=[]
for i in range(len(pd_b50_occ)):
    reco_matrix_b50.append(np.array(pd_b50_occ.iloc[i][1:]))
os.chdir("/Users/tahsinalamgirkheya/Desktop/work/reranking_fairnes/metrics")
    
from HitRation import HitRatio
hr=HitRatio(10)
alist=[]
sum_hr=0
for u in range(reco_matrix[0].shape[0]):
    x=hr.compute(all_users_tp[u],reco_matrix_b50[u])
    # alist.append(x)
    sum_hr=sum_hr+x
    # print(x)
hrb50=sum_hr/reco_matrix[0].shape[0]
hrb50
    
# reco_matrix_l49b49

0.24390243902439024

In [25]:
np.array(reco_matrix_b50)

array([[ 704,  161,  189, ...,  619,  862,  157],
       [ 843,  474,  745, ...,  785,  110,  918],
       [ 693,  371,  357, ...,    1,  101,  367],
       ...,
       [ 234,  857,  636, ...,  750,  564, 1184],
       [ 132,  747,  299, ...,  929,  665,  650],
       [1282,  106,   30, ...,  741, 1169,  797]])

In [26]:
gp_new = gp.compute(np.array(reco_matrix_b50), movies, "Occupation_Code")
gp_new

(0.09098343652802901,
 array([0.00688517, 0.00932803, 0.00759162, 0.00186737, 0.00426533,
        0.00464397, 0.00133811, 0.00377488, 0.00090177, 0.0069845 ,
        0.00533045, 0.00557802, 0.00737675, 0.00548107, 0.0048791 ,
        0.00474414, 0.0025142 , 0.00749897]))

In [33]:
gp_2 = gp.compute(np.array(reco_matrix_b70),movies)
sum(abs(gp_2))

0.05297980792010644

In [24]:
gp_3 = gp.compute(np.array(reco_matrix_l69b29),movies)
sum(abs(gp_3))

0.05702796356030189

In [25]:
#printitng results nicely



In [64]:
print("+"*50)
print("for equation \n (1 - l - b) * sum of scores for selected items (reco)\n - l * kl div of past genre prop x reco genre prop\n - b * kl div of past gender genre prop x reco genre prop)")
print("+"*50)
data = [
    ["      ","l=.29 b=.69", "l=.49 b=.49" , "l=.69 b=.29" ,"plain"], 
    ["Hitratio@10",  round(hrl29b69,4),round(hrl49b49,4), round(hrl69b29,4),round(plain_hr,4)],                              
    ["Gender Bias", round(sum(abs(gp_1)),4),round(sum(abs(gp_2)),4),round(sum(abs(gp_3)),4), 0.1561],                         
]


print("{:<12} {:<15} {:<15} {:<15} {:<15}".format(*data[0]))  
print("-" * 50)                                      
for row in data[1:]:                                
    print("{:<12} {:<15} {:<15} {:<15} {:<15}".format(*row))
    
print("+"*50)
print("for equation \n (1 - l - b) * sum of scores for selected items (reco)\n - l * kl div of past genre prop x reco genre prop\n - b * kl div of recommended gender genre prop x reco genre prop)")
print("+"*50)
data = [
    ["      ", "l=.49 b=.49" , "l=.69 b=.29" , "l=.29 b=.29" ,"plain"], 
    ["Hitratio@10",round(hr_recol49b49,4), round(hr_recol69b29,4),round(hr_recol29b29,4),round(plain_hr,4)],                              
    ["Gender Bias",round(sum(abs(gp_reco_1)),4),round(sum(abs(gp_reco_2)),4),round(sum(abs(gp_reco_3)),4), 0.1561],                         
]


print("{:<12} {:<15} {:<15} {:<15} {:<15} ".format(*data[0]))  
print("-" * 50)                                      
for row in data[1:]:                                
    print("{:<12} {:<15} {:<15} {:<15} {:<15} ".format(*row))



++++++++++++++++++++++++++++++++++++++++++++++++++
for equation 
 (1 - l - b) * sum of scores for selected items (reco)
 - l * kl div of past genre prop x reco genre prop
 - b * kl div of past gender genre prop x reco genre prop)
++++++++++++++++++++++++++++++++++++++++++++++++++
             l=.29 b=.69     l=.49 b=.49     l=.69 b=.29     plain          
--------------------------------------------------
Hitratio@10  0.2609          0.2704          0.3086          0.3595         
Gender Bias  0.0301          0.0298          0.057           0.1561         
++++++++++++++++++++++++++++++++++++++++++++++++++
for equation 
 (1 - l - b) * sum of scores for selected items (reco)
 - l * kl div of past genre prop x reco genre prop
 - b * kl div of recommended gender genre prop x reco genre prop)
++++++++++++++++++++++++++++++++++++++++++++++++++
             l=.49 b=.49     l=.69 b=.29     l=.29 b=.29     plain           
--------------------------------------------------
Hitratio@10  0.2407 

In [29]:
import os
os.chdir("/Users/tahsinalamgirkheya/Desktop/work/reranking_fairnes/metrics")


In [32]:
pdreco_l49b49= pd.read_csv("../results/reco_dist_gender/res_top10l49b49.csv",sep=",",)
    # header=None,
    # names=["userID", "itemID", "Rating"],)
reco_matrix_reco_l49b49=[]
for i in range(len(pdreco_l49b49)):
    reco_matrix_reco_l49b49.append(np.array(pdreco_l49b49.iloc[i][1:]))
    
# reco_matrix_l49b49

In [35]:

hr=HitRatio(10)
alist=[]
sum_hr=0
for u in range(reco_matrix[0].shape[0]):
    x=hr.compute(all_users_tp[u],reco_matrix_reco_l49b49[u])
    # alist.append(x)
    sum_hr=sum_hr+x
    # print(x)
hr_recol49b49=sum_hr/reco_matrix[0].shape[0]
hr_recol49b49
    

0.24072110286320256

In [37]:
gp_reco_1 = gp.compute(np.array(reco_matrix_reco_l49b49),movies)
sum(abs(gp_reco_1))

0.024419404807464518

In [43]:
pdreco_l69b29= pd.read_csv("../results/reco_dist_gender/res_topl69b29.csv",sep=",",)
    # header=None,
    # names=["userID", "itemID", "Rating"],)
reco_matrix_reco_l69b29=[]
for i in range(len(pdreco_l49b49)):
    reco_matrix_reco_l69b29.append(np.array(pdreco_l69b29.iloc[i][1:]))
    
# reco_matrix_l49b49

In [44]:

hr=HitRatio(10)
alist=[]
sum_hr=0
for u in range(reco_matrix[0].shape[0]):
    x=hr.compute(all_users_tp[u],reco_matrix_reco_l69b29[u])
    # alist.append(x)
    sum_hr=sum_hr+x
    # print(x)
hr_recol69b29=sum_hr/reco_matrix[0].shape[0]
hr_recol69b29
    

0.24284199363732767

In [61]:
gp_reco_2 = gp.compute(np.array(reco_matrix_reco_l69b29),movies)
sum(abs(gp_reco_2))

0.05035359628394449

In [49]:
pwd

'/Users/tahsinalamgirkheya/Desktop/work/reranking_fairnes/metrics'

In [50]:
pdreco_l29b29= pd.read_csv("../results/reco_dist_gender/res_top10l29b29.csv",sep=",",)
    # header=None,
    # names=["userID", "itemID", "Rating"],)
reco_matrix_reco_l29b29=[]
for i in range(len(pdreco_l29b29)):
    reco_matrix_reco_l29b29.append(np.array(pdreco_l29b29.iloc[i][1:]))
    
# reco_matrix_l49b49

In [51]:

hr=HitRatio(10)
alist=[]
sum_hr=0
for u in range(reco_matrix[0].shape[0]):
    x=hr.compute(all_users_tp[u],reco_matrix_reco_l29b29[u])
    # alist.append(x)
    sum_hr=sum_hr+x
    # print(x)
hr_recol29b29=sum_hr/reco_matrix[0].shape[0]
hr_recol29b29
    

0.271474019088017

In [53]:
gp_reco_3 = gp.compute(np.array(reco_matrix_reco_l29b29),movies)
sum(abs(gp_reco_3))

0.09345367383675837

In [56]:
pdreco_l29b69= pd.read_csv("../results/reco_dist_gender/res_top10l29b69.csv",sep=",",)
    # header=None,
    # names=["userID", "itemID", "Rating"],)
reco_matrix_reco_l29b69=[]
for i in range(len(pdreco_l29b69)):
    reco_matrix_reco_l29b69.append(np.array(pdreco_l29b69.iloc[i][1:]))
    
# reco_matrix_l49b49

In [57]:

hr=HitRatio(10)
alist=[]
sum_hr=0
for u in range(reco_matrix[0].shape[0]):
    x=hr.compute(all_users_tp[u],reco_matrix_reco_l29b69[u])
    # alist.append(x)
    sum_hr=sum_hr+x
    # print(x)
hr_recol29b69=sum_hr/reco_matrix[0].shape[0]
hr_recol29b69
    

0.22269353128313893

In [58]:
gp_reco_4 = gp.compute(np.array(reco_matrix_reco_l29b69),movies)
sum(abs(gp_reco_4))

0.04324718491385155

In [27]:
# sum score 3.3451600074768066 fairness -67.75200665458023 

(3.3451600074768066-2.2533798217773438)/4.4314069747924805

0.24637326066188947

In [31]:
(-67.75200665458023--72.5915433343418)/ -62.46890066833761

-0.07747113568487185

In [32]:
0.5*0.24637326066188947 -0.5*0.07747113568487185

0.08445106248850881

In [ ]:
score 0.24637326066188947 ft -0.07747113568487185